version: '3.5'

services:

  web:
    image: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - APP_NAME=Skills Extractor
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=project.server.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/users_test
      - SECRET_KEY=change_me_in_prod
    depends_on:
      - elasticsearch

  web-db:
    container_name: web-db
    build:
      context: ./project/server/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  elasticsearch:
    container_name: elasticsearch
    build:
      context: ./project/server/elasticsearch
      dockerfile: Dockerfile
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  rabbitmq:
    container_name: rabbitmq
    hostname:  my-rabbitmq
    build:
      context: ./project/server/rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
    environment:
      - discovery.type=single-node
      
